### ISSUE TITLE
interact.py example gives errors, import fails

### ISSUE THREAD

**Issue by nikjetchev** [Mathux/TEMOS#17]
Hi, I am really interested to try your method. I tried installing and following your advice to use the interact.py script, but get some errors that temos.data.kit cannot be found. Is there some special instruction how to install Temos, an install script in addition to the git clone? Or a proper way how to add to sys.path in python?

Thanks a lot for your help

```
 python interact.py folder=pretrained_models/kit-mmm-xyz/3l49g7hv/ saving=kick text="A person kicks with the right foot." length=60
[10/25/22 15:07:48] INFO     Interaction script. The result will be saved there: kick                   interact.py:52
                    INFO     The sentence is: A person kicks with the right foot.                       interact.py:53
[10/25/22 15:07:50] INFO     Created a temporary directory at /tmp/tmp4gjoeeh5                      instantiator.py:21
                    INFO     Writing /tmp/tmp4gjoeeh5/_remote_module_non_scriptable.py              instantiator.py:76
                    INFO     Global seed set to 1234                                                        seed.py:71
                    INFO     Loading model                                                              interact.py:71
                    INFO     Loading data module                                                        interact.py:77
Error executing job with overrides: ['folder=pretrained_models/kit-mmm-xyz/3l49g7hv/', 'saving=kick', 'text=A person kicks with the right foot.', 'length=60']
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/hydra/_internal/utils.py", line 639, in _locate
    obj = getattr(obj, part)
AttributeError: module 'temos.data' has no attribute 'kit'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/hydra/_internal/utils.py", line 645, in _locate
    obj = import_module(mod)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/content/TEMOS/temos/data/kit.py", line 15, in <module>
    from temos.transforms import Transform
  File "/content/TEMOS/temos/transforms/__init__.py", line 2, in <module>
    from .smpl import SMPLTransform
  File "/content/TEMOS/temos/transforms/smpl.py", line 8, in <module>
    from .joints2jfeats import Joints2Jfeats
  File "/content/TEMOS/temos/transforms/joints2jfeats/__init__.py", line 2, in <module>
    from .rifke import Rifke
  File "/content/TEMOS/temos/transforms/joints2jfeats/rifke.py", line 11, in <module>
    class Rifke(Joints2Jfeats):
  File "/content/TEMOS/temos/transforms/joints2jfeats/rifke.py", line 122, in Rifke
    def extract(self, features: Tensor) -> tuple[Tensor]:
TypeError: 'type' object is not subscriptable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
  File "/usr/local/lib/python3.7/dist-packages/hydra/_internal/utils.py", line 655, in _locate
    ) from exc_import
ImportError: Error loading 'temos.data.kit.KITDataModule':
TypeError("'type' object is not subscriptable")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "interact.py", line 146, in <module>
    _interact()
  File "/usr/local/lib/python3.7/dist-packages/hydra/main.py", line 95, in decorated_main
    config_name=config_name,
  File "/usr/local/lib/python3.7/dist-packages/hydra/_internal/utils.py", line 396, in _run_hydra
    overrides=overrides,
  File "/usr/local/lib/python3.7/dist-packages/hydra/_internal/utils.py", line 453, in _run_app
    lambda: hydra.run(
  File "/usr/local/lib/python3.7/dist-packages/hydra/_internal/utils.py", line 216, in run_and_report
    raise ex
  File "/usr/local/lib/python3.7/dist-packages/hydra/_internal/utils.py", line 213, in run_and_report
    return func()
  File "/usr/local/lib/python3.7/dist-packages/hydra/_internal/utils.py", line 456, in <lambda>
    overrides=overrides,
  File "/usr/local/lib/python3.7/dist-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/usr/local/lib/python3.7/dist-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/usr/local/lib/python3.7/dist-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "interact.py", line 14, in _interact
    return interact(cfg)
  File "interact.py", line 78, in interact
    data_module = instantiate(cfg.data)
  File "/usr/local/lib/python3.7/dist-packages/hydra/_internal/instantiate/_instantiate2.py", line 223, in instantiate
    config, *args, recursive=_recursive_, convert=_convert_, partial=_partial_
  File "/usr/local/lib/python3.7/dist-packages/hydra/_internal/instantiate/_instantiate2.py", line 325, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/usr/local/lib/python3.7/dist-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'temos.data.kit.KITDataModule', see chained exception above.
full_key: data
```

**Comment by Mathux** [comment]
Hi @nikjetchev,

The problem came from the fact that you did not download and install the data properly. As in this script, we don't really need the data, I updated the code to remove the dependency. 

Please ``git pull`` and then try again with the same command line and the problem should be solved.

**Comment by nikjetchev** [comment]
Hi, thanks for the answer. Your fix solved some problems, but now I get a different error message when loading the TEMOS model in code:

```
python interact.py folder=pretrained_models/kit-mmm-xyz/3l49g7hv/ saving=kick text="A person kicks with the right foot." length=60
[11/08/22 17:03:19] INFO     Interaction script. The result will be interact.py:52
                             saved there: kick                                    
                    INFO     The sentence is: A person kicks with   interact.py:53
                             the right foot.                                      
[11/08/22 17:03:24] INFO     Created a temporary directory at   instantiator.py:21
                             /tmp/tmpsef_mlmd                                     
                    INFO     Writing                            instantiator.py:76
                             /tmp/tmpsef_mlmd/_remote_module_no                   
                             n_scriptable.py                                      
                    INFO     Global seed set to 1234                    seed.py:54
                    INFO     Loading model                          interact.py:71
Error executing job with overrides: ['folder=pretrained_models/kit-mmm-xyz/3l49g7hv/', 'saving=kick', 'text=A person kicks with the right foot.', 'length=60']
Error locating target 'temos.model.temos.TEMOS', see chained exception above.
full_key: model

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

What could be wrong now, maybe a simple import or sys.path.append is missing? Hope that you can help me fix it, will be much appreciated

**Comment by lorraine-sun** [comment]
I had similar problems as @nikjetchev. I found it might be caused by python version. My python version is also 3.7 and i didn't change it to 3.9 as the author. I found a solution from
https://stackoverflow.com/questions/63460126/typeerror-type-object-is-not-subscriptable-in-a-function-signature 
and make changes on:
 ./temos/transforms/joints2jfeats/rifke.py line 122
./temos/model/textencoder/distilbert.py line 46
by removing "[xxx]" after **tuple**. It works for me.
